---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tf-controller
  namespace: cluster-config
spec:
  interval: 1h0s
  type: oci
  url: oci://ghcr.io/flux-iac/charts
